ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module
  deployment:
    port: ${APP_PORT:8080}
    host: ${APP_HOST:0.0.0.0}

  jwt:
    secret: "${JWT_SECRET:testsecret}"

database:
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  name: ${DB_NAME:testdb}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}